demo-app/saleor/dashboard/order/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^$", views.order_list, name="orders"),
    url(r"^add/$", views.order_create, name="order-create"),
    url(
        r"^(?P<order_pk>\d+)/create/$",
        views.create_order_from_draft,
        name="create-order-from-draft",
    ),
    url(r"^(?P<order_pk>\d+)/$", views.order_details, name="order-details"),
    url(r"^(?P<order_pk>\d+)/add-note/$", views.order_add_note, name="order-add-note"),
    url(r"^(?P<order_pk>\d+)/cancel/$", views.cancel_order, name="order-cancel"),
    url(
        r"^(?P<order_pk>\d+)/address/(?P<address_type>billing|shipping)/$",
        views.order_address,
        name="address-edit",
    ),
    url(
        r"^(?P<order_pk>\d+)/edit-customer/$",
        views.order_customer_edit,
        name="order-customer-edit",
    ),
    url(
        r"^(?P<order_pk>\d+)/remove-customer/$",
        views.order_customer_remove,
        name="order-customer-remove",
    ),
    url(
        r"^(?P<order_pk>\d+)/edit-shipping/$",
        views.order_shipping_edit,
        name="order-shipping-edit",
    ),
    url(
        r"^(?P<order_pk>\d+)/remove-shipping/$",
        views.order_shipping_remove,
        name="order-shipping-remove",
    ),
    url(
        r"^(?P<order_pk>\d+)/edit-discount/$",
        views.order_discount_edit,
        name="order-discount-edit",
    ),
    url(
        r"^(?P<order_pk>\d+)/edit-voucher/$",
        views.order_voucher_edit,
        name="order-voucher-edit",
    ),
    url(
        r"^(?P<order_pk>\d+)/remove-voucher/$",
        views.order_voucher_remove,
        name="order-voucher-remove",
    ),
    url(
        r"^(?P<order_pk>\d+)/delete/$",
        views.remove_draft_order,
        name="draft-order-delete",
    ),
    url(
        r"^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/capture/$",
        views.capture_payment,
        name="capture-payment",
    ),
    url(
        r"^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/void/$",
        views.void_payment,
        name="void-payment",
    ),
    url(
        r"^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/refund/$",
        views.refund_payment,
        name="refund-payment",
    ),
    url(
        r"^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/change/$",
        views.orderline_change_quantity,
        name="orderline-change-quantity",
    ),
    url(
        r"^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/cancel/$",
        views.orderline_cancel,
        name="orderline-cancel",
    ),
    url(
        r"^(?P<order_pk>\d+)/add-variant/$",
        views.add_variant_to_order,
        name="add-variant-to-order",
    ),
    url(
        r"^(?P<order_pk>\d+)/fulfill/$",
        views.fulfill_order_lines,
        name="fulfill-order-lines",
    ),
    url(
        r"^(?P<order_pk>\d+)/fulfillment/(?P<fulfillment_pk>\d+)/cancel/$",
        views.cancel_fulfillment,
        name="fulfillment-cancel",
    ),
    url(
        r"^(?P<order_pk>\d+)/fulfillment/(?P<fulfillment_pk>\d+)/tracking/$",
        views.change_fulfillment_tracking,
        name="fulfillment-change-tracking",
    ),
    url(
        r"^(?P<order_pk>\d+)/fulfillment/(?P<fulfillment_pk>\d+)/packing-slips/$",  # noqa
        views.fulfillment_packing_slips,
        name="fulfillment-packing-slips",
    ),
    url(r"^(?P<order_pk>\d+)/invoice/$", views.order_invoice, name="order-invoice"),
    url(
        r"^(?P<order_pk>\d+)/mark-as-paid/$",
        views.mark_order_as_paid,
        name="order-mark-as-paid",
    ),
    url(
        r"^(?P<order_pk>\d+)/ajax/shipping-methods/$",
        views.ajax_order_shipping_methods_list,
        name="ajax-order-shipping-methods",
    ),
]

demo-app/saleor/order/urls.py
from django.conf.urls import url

from ..core import TOKEN_PATTERN
from . import views

urlpatterns = [
    url(r"^%s/$" % (TOKEN_PATTERN,), views.details, name="details"),
    url(r"^%s/payment/$" % (TOKEN_PATTERN,), views.payment, name="payment"),
    url(
        r"^%s/payment/(?P<gateway>[-\w]+)/$" % (TOKEN_PATTERN,),
        views.start_payment,
        name="payment",
    ),
    url(
        r"^%s/cancel-payment/$" % (TOKEN_PATTERN,),
        views.cancel_payment,
        name="cancel-payment",
    ),
    url(
        r"^%s/payment-success/$" % (TOKEN_PATTERN,),
        views.payment_success,
        name="payment-success",
    ),
    url(
        r"^%s/checkout-success/$" % (TOKEN_PATTERN,),
        views.checkout_success,
        name="checkout-success",
    ),
    url(
        r"^%s/attach/$" % (TOKEN_PATTERN,),
        views.connect_order_with_user,
        name="connect-order-with-user",
    ),
]

demo-app/saleor/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.decorators.csrf import csrf_exempt
from django.views.i18n import JavaScriptCatalog, set_language

from .account.urls import urlpatterns as account_urls
from .checkout.urls import checkout_urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .graphql.api import schema
from .graphql.views import GraphQLView
from .order.urls import urlpatterns as order_urls
from .page.urls import urlpatterns as page_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls

handler404 = "saleor.core.views.handle_404"

non_translatable_urlpatterns = [
    url(r"^dashboard/", include((dashboard_urls, "dashboard"), namespace="dashboard")),
    url(r"^graphql/", csrf_exempt(GraphQLView.as_view(schema=schema)), name="api"),
    url(
        r"^sitemap\.xml$",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    url(r"^i18n/$", set_language, name="set_language"),
    url("", include("social_django.urls", namespace="social")),
]

translatable_urlpatterns = [
    url(r"^", include(core_urls)),
    url(r"^checkout/", include((checkout_urls, "checkout"), namespace="checkout")),
    url(r"^jsi18n/$", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    url(r"^order/", include((order_urls, "order"), namespace="order")),
    url(r"^page/", include((page_urls, "page"), namespace="page")),
    url(r"^products/", include((product_urls, "product"), namespace="product")),
    url(r"^account/", include((account_urls, "account"), namespace="account")),
    url(r"^feeds/", include((feed_urls, "data_feeds"), namespace="data_feeds")),
    url(r"^search/", include((search_urls, "search"), namespace="search")),
]

urlpatterns = non_translatable_urlpatterns + i18n_patterns(*translatable_urlpatterns)

if settings.DEBUG:
    try:
        import debug_toolbar
    except ImportError:
        """The debug toolbar was not installed. Ignore the error.
        settings.py should already have warned the user about it."""
    else:
        urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]

    urlpatterns += [
        # static files (images, css, javascript, etc.)
        url(r"^static/(?P<path>.*)$", serve)
    ] + static("/media/", document_root=settings.MEDIA_ROOT)

if settings.ENABLE_SILK:
    urlpatterns += [url(r"^silk/", include("silk.urls", namespace="silk"))]

demo-app/saleor/dashboard/order/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.db import transaction
from django.db.models import F, Q
from django.forms import modelformset_factory
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.context_processors import csrf
from django.template.response import TemplateResponse
from django.utils.translation import npgettext_lazy, pgettext_lazy
from django.views.decorators.http import require_POST
from django_prices.templatetags import prices_i18n

from ...core.exceptions import InsufficientStock
from ...core.utils import get_paginator_items
from ...order import OrderStatus, events
from ...order.emails import (
    send_fulfillment_confirmation_to_customer,
    send_fulfillment_update,
    send_order_confirmation,
)
from ...order.models import Fulfillment, FulfillmentLine, Order
from ...order.utils import update_order_prices, update_order_status
from ...shipping.models import ShippingMethod
from ..views import staff_member_required
from .filters import OrderFilter
from .forms import (
    AddressForm,
    AddVariantToOrderForm,
    BaseFulfillmentLineFormSet,
    CancelFulfillmentForm,
    CancelOrderForm,
    CancelOrderLineForm,
    CapturePaymentForm,
    ChangeQuantityForm,
    CreateOrderFromDraftForm,
    FulfillmentForm,
    FulfillmentLineForm,
    FulfillmentTrackingNumberForm,
    OrderCustomerForm,
    OrderEditDiscountForm,
    OrderEditVoucherForm,
    OrderMarkAsPaidForm,
    OrderNoteForm,
    OrderRemoveCustomerForm,
    OrderRemoveShippingForm,
    OrderRemoveVoucherForm,
    OrderShippingForm,
    RefundPaymentForm,
    VoidPaymentForm,
)
from .utils import (
    create_invoice_pdf,
    create_packing_slip_pdf,
    get_statics_absolute_url,
    save_address_in_order,
)


@staff_member_required
@permission_required("order.manage_orders")
def order_list(request):
    orders = Order.objects.prefetch_related("payments", "lines", "user")
    order_filter = OrderFilter(request.GET, queryset=orders)
    orders = get_paginator_items(
        order_filter.qs, settings.DASHBOARD_PAGINATE_BY, request.GET.get("page")
    )
    ctx = {
        "orders": orders,
        "filter_set": order_filter,
        "is_empty": not order_filter.queryset.exists(),
    }
    return TemplateResponse(request, "dashboard/order/list.html", ctx)


@require_POST
@staff_member_required
@permission_required("order.manage_orders")
def order_create(request):
    display_gross_prices = request.site.settings.display_gross_prices
    msg = pgettext_lazy("Dashboard message related to an order", "Draft order created")
    order = Order.objects.create(
        status=OrderStatus.DRAFT, display_gross_prices=display_gross_prices
    )

    # Create the draft creation event
    events.draft_order_created_event(order=order, user=request.user)

    # Send success message and redirect to the draft details
    messages.success(request, msg)
    return redirect("dashboard:order-details", order_pk=order.pk)


@staff_member_required
@permission_required("order.manage_orders")
def create_order_from_draft(request, order_pk):
    order = get_object_or_404(Order.objects.drafts(), pk=order_pk)
    status = 200
    form = CreateOrderFromDraftForm(request.POST or None, instance=order)
    if form.is_valid():
        form.save()
        msg = pgettext_lazy(
            "Dashboard message related to an order", "Order created from draft order"
        )

        events.order_created_event(order=order, user=request.user, from_draft=True)
        messages.success(request, msg)

        if form.cleaned_data.get("notify_customer"):
            send_order_confirmation.delay(order.pk, request.user.pk)
        return redirect("dashboard:order-details", order_pk=order.pk)
    elif form.errors:
        status = 400
    template = "dashboard/order/modal/create_order.html"
    ctx = {"form": form, "order": order}
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
@permission_required("order.manage_orders")
def remove_draft_order(request, order_pk):
    order = get_object_or_404(Order.objects.drafts(), pk=order_pk)
    if request.method == "POST":
        order.delete()
        msg = pgettext_lazy("Dashboard message", "Draft order successfully removed")
        messages.success(request, msg)
        return redirect("dashboard:orders")
    template = "dashboard/order/modal/remove_order.html"
    ctx = {"order": order}
    return TemplateResponse(request, template, ctx)


@staff_member_required
@permission_required("order.manage_orders")
def order_details(request, order_pk):
    qs = Order.objects.select_related(
        "user", "shipping_address", "billing_address"
    ).prefetch_related(
        "payments__transactions",
        "events__user",
        "lines__variant__product",
        "fulfillments__lines__order_line",
    )
    order = get_object_or_404(qs, pk=order_pk)
    all_payments = order.payments.order_by("-pk").all()
    payment = order.get_last_payment()
    ctx = {
        "order": order,
        "all_payments": all_payments,
        "payment": payment,
        "notes": order.events.filter(type=events.OrderEvents.NOTE_ADDED),
        "events": order.events.order_by("-date").all(),
        "order_fulfillments": order.fulfillments.all(),
    }
    return TemplateResponse(request, "dashboard/order/detail.html", ctx)


@staff_member_required
@permission_required("order.manage_orders")
def order_add_note(request, order_pk):
    order = get_object_or_404(Order, pk=order_pk)
    form = OrderNoteForm(request.POST or None)
    status = 200
    if form.is_valid():
        events.order_note_added_event(
            order=order, user=request.user, message=form.cleaned_data["message"]
        )
        msg = pgettext_lazy("Dashboard message related to an order", "Added note")
        messages.success(request, msg)
    elif form.errors:
        status = 400
    ctx = {"order": order, "form": form}
    ctx.update(csrf(request))
    template = "dashboard/order/modal/add_note.html"
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
@permission_required("order.manage_orders")
def capture_payment(request, order_pk, payment_pk):
    orders = Order.objects.confirmed().prefetch_related("payments")
    order = get_object_or_404(orders.prefetch_related("lines", "user"), pk=order_pk)
    payment = get_object_or_404(order.payments, pk=payment_pk)
    amount = order.total.gross
    form = CapturePaymentForm(
        request.POST or None, payment=payment, initial={"amount": amount.amount}
    )
    if form.is_valid() and form.capture(request.user):
        msg = pgettext_lazy(
            "Dashboard message related to a payment", "Captured %(amount)s"
        ) % {"amount": prices_i18n.amount(amount)}
        events.payment_captured_event(
            order=order, user=request.user, amount=amount.amount, payment=payment
        )
        messages.success(request, msg)
        return redirect("dashboard:order-details", order_pk=order.pk)
    status = 400 if form.errors else 200
    ctx = {"captured": amount, "form": form, "order": order, "payment": payment}
    return TemplateResponse(
        request, "dashboard/order/modal/capture.html", ctx, status=status
    )


@staff_member_required
@permission_required("order.manage_orders")
def refund_payment(request, order_pk, payment_pk):
    orders = Order.objects.confirmed().prefetch_related("payments")
    order = get_object_or_404(orders, pk=order_pk)
    payment = get_object_or_404(order.payments, pk=payment_pk)
    amount = payment.captured_amount
    form = RefundPaymentForm(
        request.POST or None, payment=payment, initial={"amount": amount}
    )
    if form.is_valid() and form.refund(request.user):
        amount = form.cleaned_data["amount"]
        msg = pgettext_lazy(
            "Dashboard message related to a payment", "Refunded %(amount)s"
        ) % {"amount": prices_i18n.amount(payment.get_captured_amount())}
        events.payment_refunded_event(
            order=order, user=request.user, amount=amount, payment=payment
        )
        messages.success(request, msg)
        return redirect("dashboard:order-details", order_pk=order.pk)
    status = 400 if form.errors else 200
    ctx = {
        "captured": payment.get_captured_amount(),
        "form": form,
        "order": order,
        "payment": payment,
    }
    return TemplateResponse(
        request, "dashboard/order/modal/refund.html", ctx, status=status
    )


@staff_member_required
@permission_required("order.manage_orders")
def void_payment(request, order_pk, payment_pk):
    orders = Order.objects.confirmed().prefetch_related("payments")
    order = get_object_or_404(orders, pk=order_pk)
    payment = get_object_or_404(order.payments, pk=payment_pk)
    form = VoidPaymentForm(request.POST or None, payment=payment)
    if form.is_valid() and form.void(request.user):
        msg = pgettext_lazy("Dashboard message", "Voided payment")
        events.payment_voided_event(order=order, user=request.user, payment=payment)
        messages.success(request, msg)
        return redirect("dashboard:order-details", order_pk=order.pk)
    status = 400 if form.errors else 200
    ctx = {"form": form, "order": order, "payment": payment}
    return TemplateResponse(
        request, "dashboard/order/modal/void.html", ctx, status=status
    )


@staff_member_required
@permission_required("order.manage_orders")
def orderline_change_quantity(request, order_pk, line_pk):
    orders = Order.objects.drafts().prefetch_related("lines")
    order = get_object_or_404(orders, pk=order_pk)
    line = get_object_or_404(order.lines, pk=line_pk)
    form = ChangeQuantityForm(request.POST or None, instance=line)
    status = 200
    old_quantity = line.quantity
    if form.is_valid():
        msg = pgettext_lazy(

demo-app/templates/dashboard/order/modal/add_note.html
{% extends "dashboard/base_modal.html" %}

{% load i18n %}
{% load materializecss %}

{% block action_url %}
  {% url 'dashboard:order-add-note' order_pk=order.pk %}
{% endblock %}

{% block title %}
  {% trans "Add note" context "Modal add note title" %}
{% endblock %}

{% block content %}
  {{ form|materializecss }}
{% endblock %}

{% block primary_action %}
  {% trans "Save note" context "Modal add note primary action" %}
{% endblock %}

demo-app/templates/dashboard/order/modal/add_variant_to_order.html
{% extends "dashboard/base_modal.html" %}

{% load i18n %}
{% load materializecss %}

{% block action_url %}
{% url 'dashboard:add-variant-to-order' order_pk=order.pk %}
{% endblock %}

{% block title %}
{% blocktrans trimmed with order=order context "Modal order add variant title" %}
  Add product to {{ order }}
{% endblocktrans %}
{% endblock %}

{% block content %}
{{ form.variant|materializecss:"s12 m8" }}
{{ form.quantity|materializecss:"s12 m4" }}
{% endblock %}

{% block primary_action %}
{% trans "Add" context "Modal order add variant primary action" %}
{% endblock %}

demo-app/templates/dashboard/order/modal/cancel_fulfillment.html
{% extends "dashboard/base_modal.html" %}

{% load i18n %}
{% load materializecss %}

{% block action_url %}
{% url 'dashboard:fulfillment-cancel' order_pk=order.pk fulfillment_pk=fulfillment.pk %}
{% endblock %}

{% block title %}
{% blocktrans trimmed with fulfillment=fulfillment.composed_id context "Modal cancel fulfillment title" %}
  Cancel fulfillment #{{ fulfillment }}
{% endblocktrans %}
{% endblock %}

{% block content %}
  <div class="col s12">
    {% blocktrans trimmed with fulfillment=fulfillment.composed_id context "Modal cancel fulfillment text" %}
      Are you sure you want cancel fulfillment #{{ fulfillment }}?
    {% endblocktrans %}
    {{ form.restock|materializecss }}
  </div>
{% endblock %}

{% block cancel_action %}
{% trans "Abort" context "Modal cancel fulfillment cancel action" %}
{% endblock %}

{% block primary_action %}
{% trans "Cancel Fulfillment" context "Modal cancel fulfillment primary action" %}
{% endblock %}

demo-app/templates/dashboard/order/modal/cancel_line.html
{% extends "dashboard/base_modal.html" %}

{% load i18n %}
{% load materializecss %}
{% load price from taxed_prices %}

{% block action_url %}
{% url 'dashboard:orderline-cancel' order_pk=order.pk line_pk=item.pk %}
{% endblock %}

{% block title %}
{% trans "Remove order line" context "Modal remove order line title" %}
{% endblock %}

{% block content %}
  <div class="col s12">
    {% trans "Are you sure you want remove this order line?" context "Modal remove order line text" %}
  </div>
  {{ form|materializecss }}
  <div class="col s12">
    <table>
      <thead>
        <tr>
          <th class="wide">
            {% trans "Item" context "Modal remove order line table header" %}
          </th>
          <th>
            {% trans "SKU" context "Modal remove order line table header" %}
          </th>
          <th class="right-align">
            {% trans "Price" context "Modal remove order line table header" %}
          </th>
          <th class="right-align">
            {% trans "Quantity" context "Modal remove order line table header" %}
          </th>
          <th class="right-align">
            {% trans "Total" context "Modal remove order line table header" %}
          </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            {{ item.product_name }}<br>
          </td>
          <td>
            {{ item.product_sku }}
          </td>
          <td class="right-align">
            {% price item.unit_price display_gross=order.display_gross_prices %}
          </td>
          <td class="right-align">
            {{ item.quantity }}
          </td>
          <td class="right-align">
            {% price item.get_total display_gross=order.display_gross_prices %}
          </td>
        </tr>
      </tbody>
    </table>
  </div>
{% endblock %}

{% block primary_action %}
{% trans "Remove" context "Dashboard delete action" %}
{% endblock %}

demo-app/templates/dashboard/order/modal/cancel_order.html
{% extends "dashboard/base_modal.html" %}

{% load i18n %}
{% load materializecss %}

{% block action_url %}
{% url 'dashboard:order-cancel' order_pk=order.pk %}
{% endblock %}

{% block title %}
{% trans "Cancel order" context "Modal cancel order title" %}
{% endblock %}

{% block content %}
  <div class="col s12">
    {% blocktrans trimmed with order=order context "Modal cancel order text" %}
      Are you sure you want cancel order {{ order }}?
    {% endblocktrans %}
    {{ form.restock|materializecss }}
  </div>
{% endblock %}

{% block cancel_action %}
{% trans "Abort" context "Modal cancel order cancel action" %}
{% endblock %}

{% block primary_action %}
{% trans "Cancel Order" context "Modal cancel order primary action" %}
{% endblock %}

demo-app/templates/dashboard/order/modal/capture.html
{% extends "dashboard/base_modal.html" %}

{% load babel %}
{% load i18n %}
{% load materializecss %}
{% load price from taxed_prices %}

{% block action_url %}
{% url 'dashboard:capture-payment' order_pk=order.pk payment_pk=payment.pk %}
{% endblock %}

{% block title %}
{% trans "Capture payment" context "Modal capture payment title" %}
{% endblock %}

{% block content %}
  {{ form|materializecss }}
  <div class="col s12">
    {% trans "Before this action:" context "Modal capture payment title" %}
    <ul class="list">
      <li class="list-item">{% trans "Order total:" context "Modal capture payment list title" %}
        {% price payment.order.total.gross %}
      </li>
      <li class="list-item">{% trans "Taxes (included):" context "Modal capture payment list title" %}
        {% price payment.order.total.tax %}
      </li>
      <li class="list-item">{% trans "Captured amount:" context "Modal capture payment list title" %}
        {% price captured %}
      </li>
    </ul>
  </div>
{% endblock %}

{% block primary_action %}
{% trans "Capture" context "Modal capture payment primary action" %}
{% endblock %}

demo-app/templates/dashboard/order/modal/change_quantity.html
{% extends "dashboard/base_modal.html" %}

{% load i18n %}
{% load materializecss %}

{% block action_url %}
{% url 'dashboard:orderline-change-quantity' order_pk=order.pk line_pk=object.pk %}
{% endblock %}

{% block title %}
{% trans "Change quantity" context "Modal change quantity title" %}
{% endblock %}

{% block content %}
{{ form|materializecss:"s12 m6" }}
{% endblock %}

{% block primary_action %}
{% trans "Update" context "Dashboard update action" %}
{% endblock %}

demo-app/templates/dashboard/order/modal/create_order.html
{% extends "dashboard/base_modal.html" %}

{% load i18n %}
{% load materializecss %}

{% block action_url %}
{% url 'dashboard:create-order-from-draft' order_pk=order.pk %}
{% endblock %}

{% block title %}
{% trans "Create order" context "Modal create order title" %}
{% endblock %}

{% block content %}
  <div class="col s12">
    {% blocktrans trimmed with order=order context "Modal create order text" %}
      Are you sure you want create order {{ order }}? Once the order has been created, you will not be able to make changes.
    {% endblocktrans %}
    {% if form.notify_customer %}
      {{ form.notify_customer|materializecss }}
    {% endif %}
  </div>
{% endblock %}

{% block primary_action %}
{% trans "Create" context "Modal create order primary action" %}
{% endblock %}

demo-app/templates/dashboard/order/modal/edit_shipping.html
{% extends "dashboard/base_modal.html" %}

{% load i18n %}
{% load materializecss %}

{% block action_url %}
{% url 'dashboard:order-shipping-edit' order_pk=order.pk %}
{% endblock %}

{% block title %}
{% trans "Edit shipping" context "Modal edit shipping title" %}
{% endblock %}

{% block content %}
  <div class="col s12">
    {{ form.shipping_method|materializecss }}
  </div>
{% endblock %}

{% block actions_left %}
  {% if order.shipping_method or order.shipping_method_name %}
    <button type="submit" class="modal-action btn-flat waves-effect" formaction="{% url 'dashboard:order-shipping-remove' order_pk=order.pk %}">
      {% trans "Remove shipping from order" context "Dashboard edit draft order remove action" %}
    </button>
  {% endif %}
{% endblock %}

{% block primary_action %}
{% trans "Update" context "Modal edit shipping primary action" %}
{% endblock %}

demo-app/templates/dashboard/order/modal/edit_voucher.html
{% extends "dashboard/base_modal.html" %}

{% load i18n %}
{% load materializecss %}

{% block action_url %}
{% url 'dashboard:order-voucher-edit' order_pk=order.pk %}
{% endblock %}

{% block title %}
{% trans "Edit voucher" context "Modal edit voucher title" %}
{% endblock %}

{% block content %}
  <div class="col s12">
    {{ form.voucher|materializecss }}
  </div>
{% endblock %}

{% block actions_left %}
  {% if order.voucher or order.discount_name %}
    <button type="submit" class="modal-action btn-flat waves-effect" formaction="{% url 'dashboard:order-voucher-remove' order_pk=order.pk %}">
      {% trans "Remove voucher from order" context "Dashboard edit draft order remove action" %}
    </button>
  {% endif %}
{% endblock %}

{% block primary_action %}
{% trans "Update" context "Modal edit voucher primary action" %}
{% endblock %}

demo-app/templates/dashboard/order/modal/fulfillment_tracking.html
{% extends "dashboard/base_modal.html" %}

{% load i18n %}
{% load materializecss %}

{% block action_url %}
{% url 'dashboard:fulfillment-change-tracking' order_pk=order.pk fulfillment_pk=fulfillment.pk %}
{% endblock %}

{% block title %}
{% if fulfillment.tracking_number %}
  {% trans "Edit tracking" context "Modal change fulfillment tracking title" %}
{% else %}
  {% trans "Add tracking" context "Modal change fulfillment tracking title" %}
{% endif %}
{% endblock %}

{% block content %}
  {{ form.tracking_number|materializecss }}
  {% if form.send_mail %}
    {{ form.send_mail|materializecss }}
  {% endif %}
{% endblock %}

{% block primary_action %}
{% if fulfillment.tracking_number %}
  {% trans "Update" context "Modal change fulfillment tracking primary action" %}
{% else %}
  {% trans "Save" context "Modal change fulfillment tracking primary action" %}
{% endif %}
{% endblock %}