demo-app/saleor/dashboard/discount/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"sale/$", views.sale_list, name="sale-list"),
    url(r"sale/add/$", views.sale_add, name="sale-add"),
    url(r"sale/(?P<pk>[0-9]+)/$", views.sale_edit, name="sale-update"),
    url(r"sale/(?P<pk>[0-9]+)/delete/$", views.sale_delete, name="sale-delete"),
    url(r"voucher/$", views.voucher_list, name="voucher-list"),
    url(r"voucher/add/$", views.voucher_add, name="voucher-add"),
    url(r"voucher/(?P<pk>[0-9]+)/$", views.voucher_edit, name="voucher-update"),
    url(
        r"voucher/(?P<pk>[0-9]+)/delete/$", views.voucher_delete, name="voucher-delete"
    ),
    url(r"ajax/vouchers/$", views.ajax_voucher_list, name="ajax-vouchers"),
]

demo-app/saleor/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.decorators.csrf import csrf_exempt
from django.views.i18n import JavaScriptCatalog, set_language

from .account.urls import urlpatterns as account_urls
from .checkout.urls import checkout_urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .graphql.api import schema
from .graphql.views import GraphQLView
from .order.urls import urlpatterns as order_urls
from .page.urls import urlpatterns as page_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls

handler404 = "saleor.core.views.handle_404"

non_translatable_urlpatterns = [
    url(r"^dashboard/", include((dashboard_urls, "dashboard"), namespace="dashboard")),
    url(r"^graphql/", csrf_exempt(GraphQLView.as_view(schema=schema)), name="api"),
    url(
        r"^sitemap\.xml$",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    url(r"^i18n/$", set_language, name="set_language"),
    url("", include("social_django.urls", namespace="social")),
]

translatable_urlpatterns = [
    url(r"^", include(core_urls)),
    url(r"^checkout/", include((checkout_urls, "checkout"), namespace="checkout")),
    url(r"^jsi18n/$", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    url(r"^order/", include((order_urls, "order"), namespace="order")),
    url(r"^page/", include((page_urls, "page"), namespace="page")),
    url(r"^products/", include((product_urls, "product"), namespace="product")),
    url(r"^account/", include((account_urls, "account"), namespace="account")),
    url(r"^feeds/", include((feed_urls, "data_feeds"), namespace="data_feeds")),
    url(r"^search/", include((search_urls, "search"), namespace="search")),
]

urlpatterns = non_translatable_urlpatterns + i18n_patterns(*translatable_urlpatterns)

if settings.DEBUG:
    try:
        import debug_toolbar
    except ImportError:
        """The debug toolbar was not installed. Ignore the error.
        settings.py should already have warned the user about it."""
    else:
        urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]

    urlpatterns += [
        # static files (images, css, javascript, etc.)
        url(r"^static/(?P<path>.*)$", serve)
    ] + static("/media/", document_root=settings.MEDIA_ROOT)

if settings.ENABLE_SILK:
    urlpatterns += [url(r"^silk/", include("silk.urls", namespace="silk"))]

demo-app/saleor/checkout/views/discount.py
from functools import wraps

from django.contrib import messages
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.utils import timezone
from django.utils.translation import pgettext
from django.views.decorators.http import require_POST

from ...discount.models import Voucher
from ..forms import CheckoutVoucherForm
from ..models import Checkout
from ..utils import (
    get_or_empty_db_checkout,
    recalculate_checkout_discount,
    remove_voucher_from_checkout,
)


def add_voucher_form(view):
    """Decorate a view injecting a voucher form and handling its submission."""

    @wraps(view)
    def func(request, checkout):
        prefix = "discount"
        data = {k: v for k, v in request.POST.items() if k.startswith(prefix)}
        voucher_form = CheckoutVoucherForm(
            data or None, prefix=prefix, instance=checkout
        )
        if voucher_form.is_bound:
            if voucher_form.is_valid():
                voucher_form.save()
                next_url = request.GET.get("next", request.META["HTTP_REFERER"])
                return redirect(next_url)
            else:
                remove_voucher_from_checkout(checkout)
                # if only discount form was used we clear post for other forms
                request.POST = {}
        else:
            recalculate_checkout_discount(checkout, request.discounts)
        response = view(request, checkout)
        if isinstance(response, TemplateResponse):
            response.context_data["voucher_form"] = voucher_form
        return response

    return func


def validate_voucher(view):
    """Decorate a view making it check whether a discount voucher is valid.

    If the voucher is invalid it will be removed and the user will be
    redirected to the checkout summary view.
    """

    @wraps(view)
    def func(request, checkout):
        if checkout.voucher_code:
            try:
                Voucher.objects.active(date=timezone.now()).get(
                    code=checkout.voucher_code
                )
            except Voucher.DoesNotExist:
                remove_voucher_from_checkout(checkout)
                msg = pgettext(
                    "Checkout warning",
                    "This voucher has expired. Please review your checkout.",
                )
                messages.warning(request, msg)
                return redirect("checkout:summary")
        return view(request, checkout)

    return func


@require_POST
@get_or_empty_db_checkout(Checkout.objects.for_display())
def remove_voucher_view(request, checkout):
    """Clear the discount and remove the voucher."""
    next_url = request.GET.get("next", request.META["HTTP_REFERER"])
    remove_voucher_from_checkout(checkout)
    return redirect(next_url)

demo-app/saleor/dashboard/discount/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.utils import timezone
from django.utils.translation import pgettext_lazy

from ...core.utils import get_paginator_items
from ...discount import VoucherType
from ...discount.models import Sale, Voucher
from ..views import staff_member_required
from . import forms
from .filters import SaleFilter, VoucherFilter


def get_voucher_type_forms(voucher, data):
    """Return a dict of specific voucher type forms."""
    return {
        VoucherType.SHIPPING: forms.ShippingVoucherForm(
            data or None, instance=voucher, prefix=VoucherType.SHIPPING
        ),
        VoucherType.ENTIRE_ORDER: forms.EntireOrderVoucherForm(
            data or None, instance=voucher, prefix=VoucherType.ENTIRE_ORDER
        ),
        VoucherType.SPECIFIC_PRODUCT: forms.SpecificProductVoucherForm(
            data or None, instance=voucher, prefix=VoucherType.SPECIFIC_PRODUCT
        ),
        VoucherType.PRODUCT: forms.ProductVoucherForm(
            data or None, instance=voucher, prefix=VoucherType.PRODUCT
        ),
        VoucherType.COLLECTION: forms.CollectionVoucherForm(
            data or None, instance=voucher, prefix=VoucherType.COLLECTION
        ),
        VoucherType.CATEGORY: forms.CategoryVoucherForm(
            data or None, instance=voucher, prefix=VoucherType.CATEGORY
        ),
    }


@staff_member_required
@permission_required("discount.manage_discounts")
def sale_list(request):
    sales = Sale.objects.prefetch_related("products").order_by("name")
    sale_filter = SaleFilter(request.GET, queryset=sales)
    sales = get_paginator_items(
        sale_filter.qs, settings.DASHBOARD_PAGINATE_BY, request.GET.get("page")
    )
    ctx = {
        "sales": sales,
        "filter_set": sale_filter,
        "is_empty": not sale_filter.queryset.exists(),
    }
    return TemplateResponse(request, "dashboard/discount/sale/list.html", ctx)


@staff_member_required
@permission_required("discount.manage_discounts")
def sale_add(request):
    sale = Sale()
    form = forms.SaleForm(request.POST or None, instance=sale)
    if form.is_valid():
        sale = form.save()
        msg = pgettext_lazy("Sale (discount) message", "Added sale")
        messages.success(request, msg)
        return redirect("dashboard:sale-update", pk=sale.pk)
    ctx = {"sale": sale, "form": form}
    return TemplateResponse(request, "dashboard/discount/sale/form.html", ctx)


@staff_member_required
@permission_required("discount.manage_discounts")
def sale_edit(request, pk):
    sale = get_object_or_404(Sale, pk=pk)
    form = forms.SaleForm(request.POST or None, instance=sale)
    if form.is_valid():
        sale = form.save()
        msg = pgettext_lazy("Sale (discount) message", "Updated sale")
        messages.success(request, msg)
        return redirect("dashboard:sale-update", pk=sale.pk)
    ctx = {"sale": sale, "form": form}
    return TemplateResponse(request, "dashboard/discount/sale/form.html", ctx)


@staff_member_required
@permission_required("discount.manage_discounts")
def sale_delete(request, pk):
    instance = get_object_or_404(Sale, pk=pk)
    if request.method == "POST":
        instance.delete()
        msg = pgettext_lazy("Sale (discount) message", "Removed sale %s") % (
            instance.name,
        )
        messages.success(request, msg)
        return redirect("dashboard:sale-list")
    ctx = {"sale": instance}
    return TemplateResponse(
        request, "dashboard/discount/sale/modal/confirm_delete.html", ctx
    )


@staff_member_required
@permission_required("discount.manage_discounts")
def voucher_list(request):
    vouchers = Voucher.objects.prefetch_related("products", "collections").order_by(
        "name"
    )
    voucher_filter = VoucherFilter(request.GET, queryset=vouchers)
    vouchers = get_paginator_items(
        voucher_filter.qs, settings.DASHBOARD_PAGINATE_BY, request.GET.get("page")
    )
    ctx = {
        "vouchers": vouchers,
        "filter_set": voucher_filter,
        "is_empty": not voucher_filter.queryset.exists(),
    }
    return TemplateResponse(request, "dashboard/discount/voucher/list.html", ctx)


@staff_member_required
@permission_required("discount.manage_discounts")
def voucher_add(request):
    voucher = Voucher()
    type_base_forms = get_voucher_type_forms(voucher, request.POST)
    voucher_form = forms.VoucherForm(request.POST or None, instance=voucher)
    if voucher_form.is_valid():
        voucher_type = voucher_form.cleaned_data.get("type")
        form_type = type_base_forms.get(voucher_type)

        if form_type is None:
            voucher = voucher_form.save()
        elif form_type.is_valid():
            voucher = form_type.save()

        if form_type is None or form_type.is_valid():
            msg = pgettext_lazy("Voucher message", "Added voucher")
            messages.success(request, msg)
            return redirect("dashboard:voucher-list")
    ctx = {
        "voucher": voucher,
        "default_currency": settings.DEFAULT_CURRENCY,
        "form": voucher_form,
        "type_base_forms": type_base_forms,
    }
    return TemplateResponse(request, "dashboard/discount/voucher/form.html", ctx)


@staff_member_required
@permission_required("discount.manage_discounts")
def voucher_edit(request, pk):
    voucher = get_object_or_404(Voucher, pk=pk)
    type_base_forms = get_voucher_type_forms(voucher, request.POST)
    voucher_form = forms.VoucherForm(request.POST or None, instance=voucher)
    if voucher_form.is_valid():
        voucher_type = voucher_form.cleaned_data.get("type")
        form_type = type_base_forms.get(voucher_type)

        if form_type is None:
            voucher = voucher_form.save()
        elif form_type.is_valid():
            voucher = form_type.save()

        if form_type is None or form_type.is_valid():
            msg = pgettext_lazy("Voucher message", "Updated voucher")
            messages.success(request, msg)
            return redirect("dashboard:voucher-list")
    ctx = {
        "voucher": voucher,
        "default_currency": settings.DEFAULT_CURRENCY,
        "form": voucher_form,
        "type_base_forms": type_base_forms,
    }
    return TemplateResponse(request, "dashboard/discount/voucher/form.html", ctx)


@staff_member_required
@permission_required("discount.manage_discounts")
def voucher_delete(request, pk):
    instance = get_object_or_404(Voucher, pk=pk)
    if request.method == "POST":
        instance.delete()
        msg = pgettext_lazy("Voucher message", "Removed voucher %s") % (instance,)
        messages.success(request, msg)
        return redirect("dashboard:voucher-list")
    ctx = {"voucher": instance}
    return TemplateResponse(
        request, "dashboard/discount/voucher/modal/confirm_delete.html", ctx
    )


@staff_member_required
@permission_required("discount.manage_discounts")
def ajax_voucher_list(request):
    queryset = Voucher.objects.active(date=timezone.now())

    search_query = request.GET.get("q", "")
    if search_query:
        queryset = queryset.filter(Q(name__icontains=search_query))

    vouchers = [{"id": voucher.pk, "text": str(voucher)} for voucher in queryset]
    return JsonResponse({"results": vouchers})

demo-app/templates/dashboard/discount/voucher/form.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load materializecss %}
{% load static %}

{% block title %}
  {% if voucher.pk %}
    {{ voucher }}
  {% else %}
    {% trans "Add new voucher" context "Voucher page title" %}
  {% endif %}
   - {% trans "Vouchers" context "Dashboard vouchers list" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-vouchers{% endblock %}

{% block menu_vouchers_class %}active{% endblock %}

{% block header_menu %}
  {% url "dashboard:voucher-list" as url %}
  {% include "dashboard/includes/_back_link.html" with url=url %}
{% endblock %}

{% block header_extra %}
  {% if voucher.pk %}
    <a class="dropdown-button right" href="#" data-activates="voucher-delete" data-constrainwidth="false">
      <svg data-src="{% static "dashboard/images/more-vert.svg" %}" height="24" width="24" />
    </a>
    <ul id="voucher-delete" class="dropdown-content">
      <li>
        <a class="modal-trigger-custom" href="#base-modal" data-href="{% url 'dashboard:voucher-delete' pk=voucher.pk %}">
          {% trans "Remove voucher" context "Voucher action" %}
        </a>
      </li>
    </ul>
  {% endif %}
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url 'dashboard:voucher-list' %}">
        {% trans "Vouchers" context "Dashboard vouchers list" %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url 'dashboard:voucher-list' %}">
        <svg data-src="{% static "dashboard/images/arrow-left.svg" %}" fill="#fff" width="20px" height="20px" />
      </a>
    </li>
    <li>
      <span class="breadcrumbs--ellipsed-item">
        {% if voucher.pk %}
          {{ voucher }}
        {% else %}
          {% trans "Add new voucher" context "Voucher breadcrumbs" %}
        {% endif %}
      </span>
    </li>
  </ul>
{% endblock %}

{% block menu_discounts_class %} active{% endblock %}

{% block content %}
  <div class="row">
    <div class="col m12 l9">
      <div class="card">
        <form method="post" enctype="multipart/form-data" id="form-vouchers" novalidate>
          <div class="card-content card-content-form">
            {% csrf_token %}
            {% if form.non_field_errors %}
              <blockquote>
                {% for non_field_error in form.non_field_errors %}
                  {{ non_field_error }}
                {% endfor %}
              </blockquote>
            {% endif %}
            <div class="row">
              <div class="col s12 m8">
                <div class="row">
                  {{ form.code|materializecss }}
                </div>
                <div class="row">
                  {{ form.name|materializecss }}
                </div>
                <div class="row">
                  <div class="col s12 m8">
                    <div class="row">
                      {{ form.discount_value|materializecss }}
                    </div>
                  </div>
                  <div class="col s12 m4">
                    <div class="row">
                      {{ form.discount_value_type|materializecss:"input-field s12" }}
                    </div>
                  </div>
                </div>
                <div class="row">
                  {{ form.type|materializecss:"input-field s12" }}
                </div>
                {% for form_type, form in type_base_forms.items %}
                  <div class="row voucher-form" data-type="{{ form_type }}">
                    {% for field in form %}
                      {{ field|materializecss:"input-field s12" }}
                    {% endfor %}
                  </div>
                {% endfor %}
              </div>
              <div class="col s12 m4">
                <div class="row">
                  {{ form.start_date|materializecss:"input-field s12" }}
                </div>
                <div class="row">
                  {{ form.end_date|materializecss:"input-field s12" }}
                </div>
                <div class="row">
                  {{ form.usage_limit|materializecss }}
                </div>
              </div>
            </div>
          </div>
          <div class="card-action right-align">
            <a href="{% url 'dashboard:voucher-list' %}" class="btn-flat waves-effect">
              {% trans "Cancel" context "Dashboard cancel action" %}
            </a>
            {% if voucher.pk %}
              <button type="submit" class="btn waves-effect">
                {% trans "Update" context "Dashboard update action" %}
              </button>
            {% else %}
              <button type="submit" class="btn waves-effect">
                {% trans "Create" context "Dashboard create action" %}
              </button>
            {% endif %}
          </div>
        </form>
      </div>
    </div>
    <div class="col m12 l3 help-box"></div>
  </div>
{% endblock %}

demo-app/templates/dashboard/discount/voucher/list.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load price from taxed_prices %}
{% load materializecss %}
{% load static %}
{% load utils %}

{% block title %}
  {% trans "Vouchers" context "Dashboard vouchers list" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-vouchers{% endblock %}

{% block menu_vouchers_class %}active{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs">
    <li class="visible-s">
      {% trans "Vouchers" context "Dashboard vouchers list" %}
    </li>
  </ul>
{% endblock %}

{% block menu_discounts_class %} active{% endblock %}

{% block header_extra %}
  <div class="btn-fab-fixed">
    <a href="{% url 'dashboard:voucher-add' %}" class="btn-fab-default waves-effect waves-light" title="{% trans "Add voucher" context "Voucher list add button text" %}">
      <svg data-src="{% static "dashboard/images/add.svg" %}" />
    </a>
  </div>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col s12 l9">
      {% if vouchers %}
        <div class="card">
          <div class="data-table-container">
            <table class="bordered highlight responsive data-table last-right-align">
              <thead>
                <tr>
                  {% trans "Name" context "Voucher table header" as label %}
                  {% sorting_header 'name' label is_wide=True %}

                  {% trans "Discount" context "Voucher table header" as label %}
                  {% sorting_header 'discount_value' label is_wide=True %}

                  {% trans "Start date" context "Voucher table header" as label %}
                  {% sorting_header 'start_date' label is_wide=True %}

                  {% trans "End date" context "Voucher table header" as label %}
                  {% sorting_header 'end_date' label is_wide=True %}

                  {% trans "Used" context "Voucher table header" as label %}
                  {% sorting_header 'used' label is_wide=True %}

                  {% trans "Min amount spent" context "Voucher table header" as label %}
                  {% sorting_header 'min_amount_spent' label is_wide=True %}
                </tr>
              </thead>
              {% for voucher in vouchers %}
                <tbody>
                  <tr data-action-go="{% url 'dashboard:voucher-update' pk=voucher.pk %}">
                    <td>
                      {{ voucher }}
                    </td>
                    <td class="right-align">
                      {{ voucher.discount_value }}&nbsp;<span class="currency">{{ voucher.get_discount_value_type_display }}</span>
                    </td>
                    <td>
                      {{ voucher.start_date }}
                    </td>
                    <td>
                      {{ voucher.end_date|default_if_none:"-" }}
                    </td>
                    <td class="right-align">
                      {% if voucher.usage_limit or voucher.usage_limit == 0 %}
                        {{ voucher.used }}/{{ voucher.usage_limit }}
                      {% else %}
                        {{ voucher.used }}
                      {% endif %}
                    </td>
                    <td class="right-align">
                      {% if voucher.min_amount_spent %}
                        {% price voucher.min_amount_spent %}
                      {% else %}
                        -
                      {% endif %}
                    </td>
                  </tr>
                </tbody>
              {% endfor %}
            </table>
          </div>
        </div>
        {% paginate vouchers %}
      {% else %}
        {% if is_empty %}
          {% include 'dashboard/discount/voucher/zero_page.html' %}
        {% else %}
          <div class="col s12">
            <div class="not-found">
              <p class="grey-text">
                {% trans "No vouchers found" context "Empty vouchers table message" %}
              </p>
            </div>
          </div>
        {% endif %}
      {% endif %}
      </div>
    <div class="col s12 l3" id="filters">
      {% if not is_empty %}{% filters filter_set %}{% endif %}
    </div>
  </div>
{% endblock %}

demo-app/templates/dashboard/discount/voucher/zero_page.html
{% extends 'dashboard/base_zero_page.html' %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "No vouchers found." %}{% endblock %}
{% block content %}
  {% static "dashboard/images/add.svg" as img_path %}
  {% blocktrans %}
    Vouchers allows creating promotional codes for all purchases, specific products or shipping.<br>
    You can create vouchers by using the <span class="btn-fab-presentation"><svg data-src="{{ img_path }}" /></span> button.
  {% endblocktrans %}
{% endblock %}