demo-app/saleor/dashboard/menu/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^$", views.menu_list, name="menu-list"),
    url(r"^add/$", views.menu_create, name="menu-add"),
    url(r"^(?P<pk>[0-9]+)/edit/$", views.menu_edit, name="menu-edit"),
    url(r"^(?P<pk>[0-9]+)/delete/$", views.menu_delete, name="menu-delete"),
    url(r"^(?P<pk>[0-9]+)/$", views.menu_details, name="menu-details"),
    url(r"^(?P<menu_pk>[0-9]+)/add/$", views.menu_item_create, name="menu-item-add"),
    url(
        r"^(?P<menu_pk>[0-9]+)/item/(?P<root_pk>[0-9]+)/add/$",
        views.menu_item_create,
        name="menu-item-add",
    ),
    url(
        r"^(?P<menu_pk>[0-9]+)/item/(?P<item_pk>[0-9]+)/edit/$",
        views.menu_item_edit,
        name="menu-item-edit",
    ),
    url(
        r"^(?P<menu_pk>[0-9]+)/item/(?P<item_pk>[0-9]+)/delete/$",
        views.menu_item_delete,
        name="menu-item-delete",
    ),
    url(
        r"^(?P<menu_pk>[0-9]+)/item/(?P<item_pk>[0-9]+)/$",
        views.menu_item_details,
        name="menu-item-details",
    ),
    url(
        r"^(?P<menu_pk>[0-9]+)/items/reorder/$",
        views.ajax_reorder_menu_items,
        name="menu-items-reorder",
    ),
    url(
        r"^(?P<menu_pk>[0-9]+)/item/(?P<root_pk>[0-9]+)/items/reorder/$",
        views.ajax_reorder_menu_items,
        name="menu-items-reorder",
    ),
    url(r"^ajax/links/$", views.ajax_menu_links, name="ajax-menu-links"),
]

demo-app/saleor/dashboard/page/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^$", views.page_list, name="page-list"),
    url(r"^add/$", views.page_add, name="page-add"),
    url(r"^(?P<pk>[0-9]+)/$", views.page_details, name="page-details"),
    url(r"^(?P<pk>[0-9]+)/update/$", views.page_update, name="page-update"),
    url(r"^(?P<pk>[0-9]+)/delete/$", views.page_delete, name="page-delete"),
]

demo-app/saleor/dashboard/taxes/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^$", views.tax_list, name="taxes"),
    url(
        r"^(?P<country_code>[A-Z]{2})/details/$", views.tax_details, name="tax-details"
    ),
    url(r"^configure-taxes/$", views.configure_taxes, name="configure-taxes"),
    url(r"^fetch-tax-rates/$", views.fetch_tax_rates, name="fetch-tax-rates"),
]

demo-app/saleor/dashboard/urls.py
from django.conf.urls import include, url
from django.views.generic.base import TemplateView

from . import views as core_views
from .category.urls import urlpatterns as category_urls
from .collection.urls import urlpatterns as collection_urls
from .customer.urls import urlpatterns as customer_urls
from .discount.urls import urlpatterns as discount_urls
from .menu.urls import urlpatterns as menu_urls
from .order.urls import urlpatterns as order_urls
from .page.urls import urlpatterns as page_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls
from .shipping.urls import urlpatterns as shipping_urls
from .sites.urls import urlpatterns as site_urls
from .staff.urls import urlpatterns as staff_urls
from .taxes.urls import urlpatterns as taxes_urls

urlpatterns = [
    url(r"^$", core_views.index, name="index"),
    url(r"^categories/", include(category_urls)),
    url(r"^collections/", include(collection_urls)),
    url(r"^orders/", include(order_urls)),
    url(r"^page/", include(page_urls)),
    url(r"^products/", include(product_urls)),
    url(r"^customers/", include(customer_urls)),
    url(r"^staff/", include(staff_urls)),
    url(r"^discounts/", include(discount_urls)),
    url(r"^settings/", include(site_urls)),
    url(r"^menu/", include(menu_urls)),
    url(r"^shipping/", include(shipping_urls)),
    url(r"^style-guide/", core_views.styleguide, name="styleguide"),
    url(r"^search/", include(search_urls)),
    url(r"^taxes/", include(taxes_urls)),
    url(r"^next/", TemplateView.as_view(template_name="dashboard/next.html")),
]

demo-app/saleor/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.decorators.csrf import csrf_exempt
from django.views.i18n import JavaScriptCatalog, set_language

from .account.urls import urlpatterns as account_urls
from .checkout.urls import checkout_urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .graphql.api import schema
from .graphql.views import GraphQLView
from .order.urls import urlpatterns as order_urls
from .page.urls import urlpatterns as page_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls

handler404 = "saleor.core.views.handle_404"

non_translatable_urlpatterns = [
    url(r"^dashboard/", include((dashboard_urls, "dashboard"), namespace="dashboard")),
    url(r"^graphql/", csrf_exempt(GraphQLView.as_view(schema=schema)), name="api"),
    url(
        r"^sitemap\.xml$",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    url(r"^i18n/$", set_language, name="set_language"),
    url("", include("social_django.urls", namespace="social")),
]

translatable_urlpatterns = [
    url(r"^", include(core_urls)),
    url(r"^checkout/", include((checkout_urls, "checkout"), namespace="checkout")),
    url(r"^jsi18n/$", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    url(r"^order/", include((order_urls, "order"), namespace="order")),
    url(r"^page/", include((page_urls, "page"), namespace="page")),
    url(r"^products/", include((product_urls, "product"), namespace="product")),
    url(r"^account/", include((account_urls, "account"), namespace="account")),
    url(r"^feeds/", include((feed_urls, "data_feeds"), namespace="data_feeds")),
    url(r"^search/", include((search_urls, "search"), namespace="search")),
]

urlpatterns = non_translatable_urlpatterns + i18n_patterns(*translatable_urlpatterns)

if settings.DEBUG:
    try:
        import debug_toolbar
    except ImportError:
        """The debug toolbar was not installed. Ignore the error.
        settings.py should already have warned the user about it."""
    else:
        urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]

    urlpatterns += [
        # static files (images, css, javascript, etc.)
        url(r"^static/(?P<path>.*)$", serve)
    ] + static("/media/", document_root=settings.MEDIA_ROOT)

if settings.ENABLE_SILK:
    urlpatterns += [url(r"^silk/", include("silk.urls", namespace="silk"))]

demo-app/saleor/dashboard/search/forms.py
from ...search.backends import picker
from ...search.forms import SearchForm


class DashboardSearchForm(SearchForm):
    def search(self):
        query = self.cleaned_data["q"]
        search = picker.pick_dashboard_backend()
        return search(query)

demo-app/saleor/dashboard/taxes/forms.py
from django import forms
from django.utils.translation import pgettext_lazy

from ...site.models import SiteSettings


class TaxesConfigurationForm(forms.ModelForm):
    class Meta:
        model = SiteSettings
        fields = (
            "include_taxes_in_prices",
            "display_gross_prices",
            "charge_taxes_on_shipping",
        )
        labels = {
            "include_taxes_in_prices": pgettext_lazy(
                "Include taxes in prices",
                "All products prices are entered with tax included",
            ),
            "display_gross_prices": pgettext_lazy(
                "Display gross prices",
                "Show gross prices to customers in the storefront",
            ),
            "charge_taxes_on_shipping": pgettext_lazy(
                "Charge taxes on shipping rates", "Charge taxes on shipping rates"
            ),
        }

demo-app/saleor/dashboard/category/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils.translation import pgettext_lazy

from ...core.utils import get_paginator_items
from ...product.models import Category
from ..menu.utils import get_menus_that_needs_update, update_menus
from ..views import staff_member_required
from .filters import CategoryFilter
from .forms import CategoryForm


@staff_member_required
@permission_required("product.manage_products")
def category_list(request):
    categories = Category.tree.root_nodes().order_by("name")
    category_filter = CategoryFilter(request.GET, queryset=categories)
    categories = get_paginator_items(
        category_filter.qs, settings.DASHBOARD_PAGINATE_BY, request.GET.get("page")
    )
    ctx = {
        "categories": categories,
        "filter_set": category_filter,
        "is_empty": not category_filter.queryset.exists(),
    }
    return TemplateResponse(request, "dashboard/category/list.html", ctx)


@staff_member_required
@permission_required("product.manage_products")
def category_create(request, root_pk=None):
    path = None
    category = Category()
    if root_pk:
        root = get_object_or_404(Category, pk=root_pk)
        path = root.get_ancestors(include_self=True) if root else []
    form = CategoryForm(request.POST or None, request.FILES or None, parent_pk=root_pk)
    if form.is_valid():
        category = form.save()
        messages.success(
            request, pgettext_lazy("Dashboard message", "Added category %s") % category
        )
        if root_pk:
            return redirect("dashboard:category-details", pk=root_pk)
        return redirect("dashboard:category-list")
    ctx = {"category": category, "form": form, "path": path}
    return TemplateResponse(request, "dashboard/category/form.html", ctx)


@staff_member_required
@permission_required("product.manage_products")
def category_edit(request, root_pk=None):
    path = None
    category = get_object_or_404(Category, pk=root_pk)
    if root_pk:
        root = get_object_or_404(Category, pk=root_pk)
        path = root.get_ancestors(include_self=True) if root else []
    form = CategoryForm(
        request.POST or None,
        request.FILES or None,
        instance=category,
        parent_pk=category.parent_id,
    )
    status = 200
    if form.is_valid():
        category = form.save()
        messages.success(
            request,
            pgettext_lazy("Dashboard message", "Updated category %s") % category,
        )
        if root_pk:
            return redirect("dashboard:category-details", pk=root_pk)
        return redirect("dashboard:category-list")
    elif form.errors:
        status = 400
    ctx = {"category": category, "form": form, "status": status, "path": path}
    template = "dashboard/category/form.html"
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
@permission_required("product.manage_products")
def category_details(request, pk):
    root = get_object_or_404(Category, pk=pk)
    path = root.get_ancestors(include_self=True) if root else []
    categories = root.get_children().order_by("name")
    category_filter = CategoryFilter(request.GET, queryset=categories)
    categories = get_paginator_items(
        category_filter.qs, settings.DASHBOARD_PAGINATE_BY, request.GET.get("page")
    )
    ctx = {
        "categories": categories,
        "path": path,
        "root": root,
        "filter_set": category_filter,
        "is_empty": not category_filter.queryset.exists(),
    }
    return TemplateResponse(request, "dashboard/category/detail.html", ctx)


@staff_member_required
@permission_required("product.manage_products")
def category_delete(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == "POST":
        descendants = category.get_descendants()
        menus = get_menus_that_needs_update(categories=descendants)
        category.delete()
        if menus:
            update_menus(menus)
        messages.success(
            request,
            pgettext_lazy("Dashboard message", "Removed category %s") % category,
        )
        root_pk = None
        if category.parent:
            root_pk = category.parent.pk
        if root_pk:
            if request.is_ajax():
                response = {
                    "redirectUrl": reverse(
                        "dashboard:category-details", kwargs={"pk": root_pk}
                    )
                }
                return JsonResponse(response)
            return redirect("dashboard:category-details", pk=root_pk)
        else:
            if request.is_ajax():
                response = {"redirectUrl": reverse("dashboard:category-list")}
                return JsonResponse(response)
            return redirect("dashboard:category-list")
    ctx = {
        "category": category,
        "descendants": list(category.get_descendants()),
        "products_count": len(category.products.all()),
    }
    return TemplateResponse(
        request, "dashboard/category/modal/confirm_delete.html", ctx
    )

demo-app/saleor/dashboard/collection/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils.translation import pgettext_lazy
from django.views.decorators.http import require_POST

from ...core.utils import get_paginator_items
from ...product.models import Collection
from ..menu.utils import get_menus_that_needs_update, update_menus
from ..views import staff_member_required
from .filters import CollectionFilter
from .forms import AssignHomepageCollectionForm, CollectionForm


@staff_member_required
@permission_required("product.manage_products")
def collection_list(request):
    site_settings = request.site.settings
    assign_homepage_col_form = AssignHomepageCollectionForm(
        request.POST or None, instance=site_settings
    )
    if request.method == "POST" and assign_homepage_col_form.is_valid():
        assign_homepage_col_form.save()
        msg = pgettext_lazy("Dashboard message", "Updated homepage collection")
        messages.success(request, msg)
        return redirect("dashboard:collection-list")
    collections = Collection.objects.prefetch_related("products").all()
    collection_filter = CollectionFilter(request.GET, queryset=collections)
    collections = get_paginator_items(
        collection_filter.qs, settings.DASHBOARD_PAGINATE_BY, request.GET.get("page")
    )
    ctx = {
        "collections": collections,
        "filter_set": collection_filter,
        "is_empty": not collection_filter.queryset.exists(),
        "assign_homepage_col_form": assign_homepage_col_form,
    }
    return TemplateResponse(request, "dashboard/collection/list.html", ctx)


@staff_member_required
@permission_required("product.manage_products")
def collection_create(request):
    collection = Collection()
    form = CollectionForm(
        request.POST or None, request.FILES or None, instance=collection
    )
    if form.is_valid():
        form.save()
        msg = pgettext_lazy("Collection message", "Added collection")
        messages.success(request, msg)
        return redirect("dashboard:collection-list")
    ctx = {"collection": collection, "form": form}
    return TemplateResponse(request, "dashboard/collection/detail.html", ctx)


@staff_member_required
@permission_required("product.manage_products")
def collection_update(request, pk=None):
    collection = get_object_or_404(Collection, pk=pk)
    form = CollectionForm(
        request.POST or None, request.FILES or None, instance=collection
    )
    if form.is_valid():
        collection = form.save()
        msg = pgettext_lazy("Collection message", "Updated collection")
        messages.success(request, msg)
        return redirect("dashboard:collection-update", pk=collection.pk)
    is_unpublish_restricted = (
        collection == request.site.settings.homepage_collection
        and collection.is_published
    )
    ctx = {
        "collection": collection,
        "form": form,
        "is_unpublish_restricted": is_unpublish_restricted,
    }
    return TemplateResponse(request, "dashboard/collection/detail.html", ctx)


@staff_member_required
@permission_required("product.manage_products")
def collection_delete(request, pk=None):
    collection = get_object_or_404(Collection, pk=pk)
    if request.method == "POST":
        menus = get_menus_that_needs_update(collection=collection)
        collection.delete()
        if menus:
            update_menus(menus)
        msg = pgettext_lazy("Collection message", "Deleted collection")
        messages.success(request, msg)
        if request.is_ajax():
            response = {"redirectUrl": reverse("dashboard:collection-list")}
            return JsonResponse(response)
        return redirect("dashboard:collection-list")
    ctx = {"collection": collection}
    return TemplateResponse(request, "dashboard/collection/confirm_delete.html", ctx)


@require_POST
@staff_member_required
@permission_required("product.manage_products")
def collection_toggle_is_published(request, pk):
    collection = get_object_or_404(Collection, pk=pk)
    collection.is_published = not collection.is_published
    collection.save(update_fields=["is_published"])
    return JsonResponse({"success": True, "is_published": collection.is_published})

demo-app/templates/dashboard/taxes/details.html
{% extends 'dashboard/base.html' %}

{% load get_country_by_code from dashboard %}
{% load i18n %}
{% load static %}

{% block title %}
  {% get_country_by_code tax.country_code as country_name %}
  {{ country_name }} tax rates - {{ block.super }}
{% endblock %}

{% block menu_taxes_class %} active{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url 'dashboard:taxes' %}">
        {% trans "Taxes" context "Tax details breadcrumbs" %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url 'dashboard:taxes' %}"><i class="material-icons">arrow_back</i></a>
    </li>
    <li>
      <span class="breadcrumbs--elipsed-item">
        {% get_country_by_code tax.country_code as country_name %}
        {{ country_name }}
      </span>
    </li>
  </ul>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col m12 l9">
      <div class="card">
        <div class="card-content">
          <span class="card-title">
            {% get_country_by_code tax.country_code as country_name %}
            {% blocktrans trimmed with country_name=country_name context "Country tax rates list title" %}
              Tax rates in {{ country_name }}
            {% endblocktrans %}
          </span>
        </div>
        <div class="data-table-container">
          <table class="bordered highlight responsive data-table">
            <thead>
              <tr>
                <th>
                  {% trans "Name" context "Country tax rates list header" %}
                </th>
                <th class="right-align">
                  {% trans "Value" context "Country tax rates list header" %}
                </th>
              </tr>
            </thead>
            <tbody>
              {% for name, tax_rate in tax_rates %}
                <tr>
                  <td>{{ name }}</td>
                  <td class="right-align">
                    {% blocktrans with tax_rate=tax_rate context "Order line tax rate value" %}
                      {{ tax_rate }} %
                    {% endblocktrans %}
                  </td>
                </tr>
              {% empty %}
                <tr>
                  <td colspan="2">{% trans "No tax rates" context "Empty country tax rates list" %}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

demo-app/templates/dashboard/taxes/form.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% load i18n %}
{% load materializecss %}

{% block title %}
  {% if site.pk %}
    {{ site }}
  {% else %}
    {% trans "Add new site settings" context "Site settings page title" %}
  {% endif %}
   - {% trans "Site settings" context "Dashboard site settings" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-settings{% endblock %}

{% block menu_taxes_class %}active{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url 'dashboard:taxes' %}" class="breadcrumbs--ellipsed-item">
        {% trans "Taxes" context "Dashboard taxes list" %}
      </a>
    </li>
    <li>
      <span>
        {% trans "Configure taxes" context "Dashboard configure taxes settings" %}
      </span>
    </li>
  </ul>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col s12 l9">
      <div class="card">
        <form method="post" id="form-category" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
          <div class="card-content card-content-form">
            <div class="card-title">
              {% trans "Taxes" context "Dashboard site taxes settings form title" %}
            </div>
            <br>
            <div class="col s12">
              <h4>{% trans "Dashboard" %}</h4>
            </div>
            <div class="row">
              <div class="col s12">
                {{ taxes_form.include_taxes_in_prices|materializecss }}
              </div>
              <div class="col s12 checkbox-helptext">
                <h6>
                  {% blocktrans context "Dashboard site taxes settings form help text" %}
                    If selected, taxes will be calculated using below formula:
                  {% endblocktrans %}
                </h6>
                <h6>
                  {% blocktrans context "Dashboard site taxes settings form help text" %}
                    tax_amount = (tax_rate * price) / (1 + tax_rate)
                  {% endblocktrans %}
                </h6>
                <h6>
                  {% blocktrans context "Dashboard site taxes settings form help text" %}
                    For example: product with price 4.00 € and 19% VAT will have net price calculated to 3.36 € and tax to 0.64 € (rounded)
                  {% endblocktrans %}
                </h6>
              </div>
            </div>
            <div class="col s12">
              <h4>{% trans "Storefront" %}</h4>
            </div>
            <div class="row">
              <div class="col s12">
                {{ taxes_form.display_gross_prices|materializecss }}
              </div>
              <div class="col s12 checkbox-helptext">
                <h6>
                  {% blocktrans context "Dashboard site taxes settings form help text" %}
                    If selected, prices displayed for customers in the storefront will be gross and taxes will be calculated at checkout.
                  {% endblocktrans %}
                </h6>
              </div>
            </div>
            <div class="row">
              <div class="col s12">
                {{ taxes_form.charge_taxes_on_shipping|materializecss }}
              </div>
              <div class="col s12 checkbox-helptext">
                <h6>
                  {% blocktrans context "Dashboard site taxes settings form help text" %}
                    If selected, standard tax rate will be charged on a shipping price.
                  {% endblocktrans %}
                </h6>
              </div>
            </div>
          </div>
          <div class="card-action right-align">
            <a class="btn-flat waves-effect" href="{% url 'dashboard:taxes' %}">
              {% trans "Cancel" context "Dashboard cancel action" %}
            </a>
            <button type="submit" class="btn waves-effect">
              {% trans "Update" context "Dashboard update action" %}
            </button>
          </div>
        </form>
      </div>
    </div>
    <div class="col m12 l3 help-box">
      <p class="grey-text">
        <svg data-src="{% static "dashboard/images/help.svg" %}" width="18" height="18" />
        {% blocktrans trimmed context "Taxes help text" %}
          Taxes are charged according to the rates applicable in the country to which the order is delivered. For now, only rates in European Union are handled.
        {% endblocktrans %}
      </p>
    </div>
  </div>
{% endblock %}

demo-app/templates/dashboard/taxes/list.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load get_country_by_code from dashboard %}
{% load utils %}

{% block title %}
  {% trans "Taxes" context "Dashboard taxes list" %} - {{ block.super }}
{% endblock %}

{% block menu_taxes_class %}active{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs">
    <li class="visible-s">
      {% trans "Taxes" context "Dashboard taxes list" %}
    </li>
  </ul>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col s12 l9">
      {% if taxes %}
        <div class="card">
          <div class="data-table-container">
            <table class="bordered highlight responsive data-table">
              <thead>
                <tr>
                  {% trans "Country code" context "Taxes table header" as label %}
                  {% sorting_header 'country_code' label %}

                  <th class="wide">
                    {% trans "Country name" context "Taxes table header" %}
                  </th>
                </tr>
              </thead>
              <tbody>
                {% for tax in taxes %}
                  <tr data-action-go="{% url 'dashboard:tax-details' country_code=tax.country_code %}">
                    <td>
                      {{ tax.country_code }}
                    </td>
                    <td>
                      {% get_country_by_code tax.country_code as country_name %}
                      {{ country_name }}
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      {% paginate taxes %}
      {% else %}
        {% if is_empty %}
          {% include 'dashboard/taxes/zero_page.html' %}
        {% else %}
          <div class="col s12">
            <div class="not-found">
              <p class="grey-text">
                {% trans "No taxes found." context "Empty taxes message" %}
              </p>
            </div>
          </div>
        {% endif %}
      {% endif %}
    </div>
    <div class="col s12 l3" id="filters">
      {% if not is_empty %}{% filters filter_set %}{% endif %}
    </div>
    <div class="col s12 l3">
      <div class="card">
        <div class="card-content">
          <span class="card-title">
            {% trans "Configuration" context "Taxes site settings title" %}
          </span>
          <div class="row">
            <div class="col s12">
              <h4>
                {% trans "All products prices are entered with tax included" context "Site settings field" %}
              </h4>
              <p>
                {% if site.settings.include_taxes_in_prices %}
                  {% trans "Yes" context "Include taxes in prices setting description" %}
                {% else %}
                  {% trans "No" context "Include taxes in prices setting description" %}
                {% endif %}
              </p>
            </div>
          </div>
          <div class="row">
            <div class="col s12">
              <h4>
                {% trans "Show gross prices to customers in the storefront" context "Site settings field" %}
              </h4>
              <p>
                {% if site.settings.display_gross_prices %}
                  {% trans "Yes" context "Show customers gross prices setting description" %}
                {% else %}
                  {% trans "No" context "Show customers gross prices setting description" %}
                {% endif %}
              </p>
            </div>
          </div>
          <div class="row">
            <div class="col s12">
              <h4>
                {% trans "Charge taxes on shipping rates" context "Site settings field" %}
              </h4>
              <p>
                {% if site.settings.charge_taxes_on_shipping %}
                  {% trans "Yes" context "Charge taxes on shipping rates setting description" %}
                {% else %}
                  {% trans "No" context "Charge taxes on shipping rates setting description" %}
                {% endif %}
              </p>
            </div>
          </div>
        </div>
        <div class="card-action">
          <a class="btn-flat waves-effect" href="{% url 'dashboard:configure-taxes' %}">
            {% trans "Configure taxes" context "Site settings configure taxes action" %}
          </a>
          <form method="POST" action="{% url 'dashboard:fetch-tax-rates' %}" style="display: inline">
            <button type="submit" class="btn-flat waves-effect">
              {% csrf_token %}
              {% trans "Fetch tax rates" context "Site settings fetch tax rates action" %}
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

demo-app/templates/dashboard/taxes/zero_page.html
{% extends 'dashboard/base_zero_page.html' %}
{% load i18n %}

{% block title %}{% trans "No taxes found." %}{% endblock %}
{% block content %}
  {% blocktrans %}
    Taxes define tax rates used in European Union countries and needs to be fetched manually.<br>
    To enable fetching taxes, please provide your access key to <a href="https://vatlayer.com/">vatlayer</a> API in settings file.
  {% endblocktrans %}
{% endblock %}