demo-app/saleor/dashboard/menu/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^$", views.menu_list, name="menu-list"),
    url(r"^add/$", views.menu_create, name="menu-add"),
    url(r"^(?P<pk>[0-9]+)/edit/$", views.menu_edit, name="menu-edit"),
    url(r"^(?P<pk>[0-9]+)/delete/$", views.menu_delete, name="menu-delete"),
    url(r"^(?P<pk>[0-9]+)/$", views.menu_details, name="menu-details"),
    url(r"^(?P<menu_pk>[0-9]+)/add/$", views.menu_item_create, name="menu-item-add"),
    url(
        r"^(?P<menu_pk>[0-9]+)/item/(?P<root_pk>[0-9]+)/add/$",
        views.menu_item_create,
        name="menu-item-add",
    ),
    url(
        r"^(?P<menu_pk>[0-9]+)/item/(?P<item_pk>[0-9]+)/edit/$",
        views.menu_item_edit,
        name="menu-item-edit",
    ),
    url(
        r"^(?P<menu_pk>[0-9]+)/item/(?P<item_pk>[0-9]+)/delete/$",
        views.menu_item_delete,
        name="menu-item-delete",
    ),
    url(
        r"^(?P<menu_pk>[0-9]+)/item/(?P<item_pk>[0-9]+)/$",
        views.menu_item_details,
        name="menu-item-details",
    ),
    url(
        r"^(?P<menu_pk>[0-9]+)/items/reorder/$",
        views.ajax_reorder_menu_items,
        name="menu-items-reorder",
    ),
    url(
        r"^(?P<menu_pk>[0-9]+)/item/(?P<root_pk>[0-9]+)/items/reorder/$",
        views.ajax_reorder_menu_items,
        name="menu-items-reorder",
    ),
    url(r"^ajax/links/$", views.ajax_menu_links, name="ajax-menu-links"),
]

demo-app/saleor/dashboard/page/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^$", views.page_list, name="page-list"),
    url(r"^add/$", views.page_add, name="page-add"),
    url(r"^(?P<pk>[0-9]+)/$", views.page_details, name="page-details"),
    url(r"^(?P<pk>[0-9]+)/update/$", views.page_update, name="page-update"),
    url(r"^(?P<pk>[0-9]+)/delete/$", views.page_delete, name="page-delete"),
]

demo-app/saleor/dashboard/urls.py
from django.conf.urls import include, url
from django.views.generic.base import TemplateView

from . import views as core_views
from .category.urls import urlpatterns as category_urls
from .collection.urls import urlpatterns as collection_urls
from .customer.urls import urlpatterns as customer_urls
from .discount.urls import urlpatterns as discount_urls
from .menu.urls import urlpatterns as menu_urls
from .order.urls import urlpatterns as order_urls
from .page.urls import urlpatterns as page_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls
from .shipping.urls import urlpatterns as shipping_urls
from .sites.urls import urlpatterns as site_urls
from .staff.urls import urlpatterns as staff_urls
from .taxes.urls import urlpatterns as taxes_urls

urlpatterns = [
    url(r"^$", core_views.index, name="index"),
    url(r"^categories/", include(category_urls)),
    url(r"^collections/", include(collection_urls)),
    url(r"^orders/", include(order_urls)),
    url(r"^page/", include(page_urls)),
    url(r"^products/", include(product_urls)),
    url(r"^customers/", include(customer_urls)),
    url(r"^staff/", include(staff_urls)),
    url(r"^discounts/", include(discount_urls)),
    url(r"^settings/", include(site_urls)),
    url(r"^menu/", include(menu_urls)),
    url(r"^shipping/", include(shipping_urls)),
    url(r"^style-guide/", core_views.styleguide, name="styleguide"),
    url(r"^search/", include(search_urls)),
    url(r"^taxes/", include(taxes_urls)),
    url(r"^next/", TemplateView.as_view(template_name="dashboard/next.html")),
]

demo-app/saleor/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.decorators.csrf import csrf_exempt
from django.views.i18n import JavaScriptCatalog, set_language

from .account.urls import urlpatterns as account_urls
from .checkout.urls import checkout_urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .graphql.api import schema
from .graphql.views import GraphQLView
from .order.urls import urlpatterns as order_urls
from .page.urls import urlpatterns as page_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls

handler404 = "saleor.core.views.handle_404"

non_translatable_urlpatterns = [
    url(r"^dashboard/", include((dashboard_urls, "dashboard"), namespace="dashboard")),
    url(r"^graphql/", csrf_exempt(GraphQLView.as_view(schema=schema)), name="api"),
    url(
        r"^sitemap\.xml$",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    url(r"^i18n/$", set_language, name="set_language"),
    url("", include("social_django.urls", namespace="social")),
]

translatable_urlpatterns = [
    url(r"^", include(core_urls)),
    url(r"^checkout/", include((checkout_urls, "checkout"), namespace="checkout")),
    url(r"^jsi18n/$", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    url(r"^order/", include((order_urls, "order"), namespace="order")),
    url(r"^page/", include((page_urls, "page"), namespace="page")),
    url(r"^products/", include((product_urls, "product"), namespace="product")),
    url(r"^account/", include((account_urls, "account"), namespace="account")),
    url(r"^feeds/", include((feed_urls, "data_feeds"), namespace="data_feeds")),
    url(r"^search/", include((search_urls, "search"), namespace="search")),
]

urlpatterns = non_translatable_urlpatterns + i18n_patterns(*translatable_urlpatterns)

if settings.DEBUG:
    try:
        import debug_toolbar
    except ImportError:
        """The debug toolbar was not installed. Ignore the error.
        settings.py should already have warned the user about it."""
    else:
        urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]

    urlpatterns += [
        # static files (images, css, javascript, etc.)
        url(r"^static/(?P<path>.*)$", serve)
    ] + static("/media/", document_root=settings.MEDIA_ROOT)

if settings.ENABLE_SILK:
    urlpatterns += [url(r"^silk/", include("silk.urls", namespace="silk"))]

demo-app/saleor/dashboard/search/forms.py
from ...search.backends import picker
from ...search.forms import SearchForm


class DashboardSearchForm(SearchForm):
    def search(self):
        query = self.cleaned_data["q"]
        search = picker.pick_dashboard_backend()
        return search(query)

demo-app/saleor/dashboard/taxes/forms.py
from django import forms
from django.utils.translation import pgettext_lazy

from ...site.models import SiteSettings


class TaxesConfigurationForm(forms.ModelForm):
    class Meta:
        model = SiteSettings
        fields = (
            "include_taxes_in_prices",
            "display_gross_prices",
            "charge_taxes_on_shipping",
        )
        labels = {
            "include_taxes_in_prices": pgettext_lazy(
                "Include taxes in prices",
                "All products prices are entered with tax included",
            ),
            "display_gross_prices": pgettext_lazy(
                "Display gross prices",
                "Show gross prices to customers in the storefront",
            ),
            "charge_taxes_on_shipping": pgettext_lazy(
                "Charge taxes on shipping rates", "Charge taxes on shipping rates"
            ),
        }

demo-app/saleor/dashboard/category/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils.translation import pgettext_lazy

from ...core.utils import get_paginator_items
from ...product.models import Category
from ..menu.utils import get_menus_that_needs_update, update_menus
from ..views import staff_member_required
from .filters import CategoryFilter
from .forms import CategoryForm


@staff_member_required
@permission_required("product.manage_products")
def category_list(request):
    categories = Category.tree.root_nodes().order_by("name")
    category_filter = CategoryFilter(request.GET, queryset=categories)
    categories = get_paginator_items(
        category_filter.qs, settings.DASHBOARD_PAGINATE_BY, request.GET.get("page")
    )
    ctx = {
        "categories": categories,
        "filter_set": category_filter,
        "is_empty": not category_filter.queryset.exists(),
    }
    return TemplateResponse(request, "dashboard/category/list.html", ctx)


@staff_member_required
@permission_required("product.manage_products")
def category_create(request, root_pk=None):
    path = None
    category = Category()
    if root_pk:
        root = get_object_or_404(Category, pk=root_pk)
        path = root.get_ancestors(include_self=True) if root else []
    form = CategoryForm(request.POST or None, request.FILES or None, parent_pk=root_pk)
    if form.is_valid():
        category = form.save()
        messages.success(
            request, pgettext_lazy("Dashboard message", "Added category %s") % category
        )
        if root_pk:
            return redirect("dashboard:category-details", pk=root_pk)
        return redirect("dashboard:category-list")
    ctx = {"category": category, "form": form, "path": path}
    return TemplateResponse(request, "dashboard/category/form.html", ctx)


@staff_member_required
@permission_required("product.manage_products")
def category_edit(request, root_pk=None):
    path = None
    category = get_object_or_404(Category, pk=root_pk)
    if root_pk:
        root = get_object_or_404(Category, pk=root_pk)
        path = root.get_ancestors(include_self=True) if root else []
    form = CategoryForm(
        request.POST or None,
        request.FILES or None,
        instance=category,
        parent_pk=category.parent_id,
    )
    status = 200
    if form.is_valid():
        category = form.save()
        messages.success(
            request,
            pgettext_lazy("Dashboard message", "Updated category %s") % category,
        )
        if root_pk:
            return redirect("dashboard:category-details", pk=root_pk)
        return redirect("dashboard:category-list")
    elif form.errors:
        status = 400
    ctx = {"category": category, "form": form, "status": status, "path": path}
    template = "dashboard/category/form.html"
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
@permission_required("product.manage_products")
def category_details(request, pk):
    root = get_object_or_404(Category, pk=pk)
    path = root.get_ancestors(include_self=True) if root else []
    categories = root.get_children().order_by("name")
    category_filter = CategoryFilter(request.GET, queryset=categories)
    categories = get_paginator_items(
        category_filter.qs, settings.DASHBOARD_PAGINATE_BY, request.GET.get("page")
    )
    ctx = {
        "categories": categories,
        "path": path,
        "root": root,
        "filter_set": category_filter,
        "is_empty": not category_filter.queryset.exists(),
    }
    return TemplateResponse(request, "dashboard/category/detail.html", ctx)


@staff_member_required
@permission_required("product.manage_products")
def category_delete(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == "POST":
        descendants = category.get_descendants()
        menus = get_menus_that_needs_update(categories=descendants)
        category.delete()
        if menus:
            update_menus(menus)
        messages.success(
            request,
            pgettext_lazy("Dashboard message", "Removed category %s") % category,
        )
        root_pk = None
        if category.parent:
            root_pk = category.parent.pk
        if root_pk:
            if request.is_ajax():
                response = {
                    "redirectUrl": reverse(
                        "dashboard:category-details", kwargs={"pk": root_pk}
                    )
                }
                return JsonResponse(response)
            return redirect("dashboard:category-details", pk=root_pk)
        else:
            if request.is_ajax():
                response = {"redirectUrl": reverse("dashboard:category-list")}
                return JsonResponse(response)
            return redirect("dashboard:category-list")
    ctx = {
        "category": category,
        "descendants": list(category.get_descendants()),
        "products_count": len(category.products.all()),
    }
    return TemplateResponse(
        request, "dashboard/category/modal/confirm_delete.html", ctx
    )

demo-app/saleor/dashboard/collection/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils.translation import pgettext_lazy
from django.views.decorators.http import require_POST

from ...core.utils import get_paginator_items
from ...product.models import Collection
from ..menu.utils import get_menus_that_needs_update, update_menus
from ..views import staff_member_required
from .filters import CollectionFilter
from .forms import AssignHomepageCollectionForm, CollectionForm


@staff_member_required
@permission_required("product.manage_products")
def collection_list(request):
    site_settings = request.site.settings
    assign_homepage_col_form = AssignHomepageCollectionForm(
        request.POST or None, instance=site_settings
    )
    if request.method == "POST" and assign_homepage_col_form.is_valid():
        assign_homepage_col_form.save()
        msg = pgettext_lazy("Dashboard message", "Updated homepage collection")
        messages.success(request, msg)
        return redirect("dashboard:collection-list")
    collections = Collection.objects.prefetch_related("products").all()
    collection_filter = CollectionFilter(request.GET, queryset=collections)
    collections = get_paginator_items(
        collection_filter.qs, settings.DASHBOARD_PAGINATE_BY, request.GET.get("page")
    )
    ctx = {
        "collections": collections,
        "filter_set": collection_filter,
        "is_empty": not collection_filter.queryset.exists(),
        "assign_homepage_col_form": assign_homepage_col_form,
    }
    return TemplateResponse(request, "dashboard/collection/list.html", ctx)


@staff_member_required
@permission_required("product.manage_products")
def collection_create(request):
    collection = Collection()
    form = CollectionForm(
        request.POST or None, request.FILES or None, instance=collection
    )
    if form.is_valid():
        form.save()
        msg = pgettext_lazy("Collection message", "Added collection")
        messages.success(request, msg)
        return redirect("dashboard:collection-list")
    ctx = {"collection": collection, "form": form}
    return TemplateResponse(request, "dashboard/collection/detail.html", ctx)


@staff_member_required
@permission_required("product.manage_products")
def collection_update(request, pk=None):
    collection = get_object_or_404(Collection, pk=pk)
    form = CollectionForm(
        request.POST or None, request.FILES or None, instance=collection
    )
    if form.is_valid():
        collection = form.save()
        msg = pgettext_lazy("Collection message", "Updated collection")
        messages.success(request, msg)
        return redirect("dashboard:collection-update", pk=collection.pk)
    is_unpublish_restricted = (
        collection == request.site.settings.homepage_collection
        and collection.is_published
    )
    ctx = {
        "collection": collection,
        "form": form,
        "is_unpublish_restricted": is_unpublish_restricted,
    }
    return TemplateResponse(request, "dashboard/collection/detail.html", ctx)


@staff_member_required
@permission_required("product.manage_products")
def collection_delete(request, pk=None):
    collection = get_object_or_404(Collection, pk=pk)
    if request.method == "POST":
        menus = get_menus_that_needs_update(collection=collection)
        collection.delete()
        if menus:
            update_menus(menus)
        msg = pgettext_lazy("Collection message", "Deleted collection")
        messages.success(request, msg)
        if request.is_ajax():
            response = {"redirectUrl": reverse("dashboard:collection-list")}
            return JsonResponse(response)
        return redirect("dashboard:collection-list")
    ctx = {"collection": collection}
    return TemplateResponse(request, "dashboard/collection/confirm_delete.html", ctx)


@require_POST
@staff_member_required
@permission_required("product.manage_products")
def collection_toggle_is_published(request, pk):
    collection = get_object_or_404(Collection, pk=pk)
    collection.is_published = not collection.is_published
    collection.save(update_fields=["is_published"])
    return JsonResponse({"success": True, "is_published": collection.is_published})

demo-app/templates/dashboard/includes/_address.html
{% load i18n_address_tags %}
{% load static %}

<div class="address">
	{% format_address address include_phone=False latin=True %}
	{% if address.phone %}
		<div>
			<svg data-src="{% static "dashboard/images/phone.svg" %}" width="16" height="16" class="left" />
			<a href="tel:{{ address.phone }}" class="phone-number">
				{{ address.phone }}
			</a>
		</div>
	{% endif %}
</div>

demo-app/templates/dashboard/includes/_back_link.html
<a href="{{ url }}{% if hash %}{{ hash }}{% endif %}" class="header-button">
  <svg data-src="{% static "dashboard/images/arrow-left.svg" %}" fill="#fff" width="20px" height="20px" />
</a>

demo-app/templates/dashboard/includes/_bulk_actions_bar.html
{% load static %}

<nav class="data-table-bulk-actions">
  <div class="data-table-bulk-actions__select-all"></div>
  <div class="data-table-bulk-actions__selected-items col inline"></div>
  <div class="data-table-bulk-actions__action-choice">
    <ul class="right">
      {% for action, label in bulk_action_form.action.field.widget.choices %}
        <li>
          <a href=""
             data-action="{{ action }}"
             class="btn-flat waves-effect">{{ label|upper }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
  <div class="data-table-bulk-actions__dropdown-container">
    <a class="dropdown-button right" href="#!" data-activates="dropdown-bulk-actions" data-constrainwidth="false" data-gutter="-19" data-alignment="right">
      <svg data-src="{% static "dashboard/images/more-vert.svg" %}" height="24" width="24" />
    </a>
    <ul id="dropdown-bulk-actions" class="dropdown-content">
    {% for action, label in bulk_action_form.action.field.widget.choices %}
      <li>
        <a href=""
           data-action="{{ action }}"
           class="btn-flat waves-effect">{{ label|upper }}</a>
      </li>
    {% endfor %}
  </ul>
  </div>
</nav>

demo-app/templates/dashboard/includes/_collection_availability.html
{% load i18n %}

<div class="label label-{{ label_cls }}">
  {% if is_visible %}
    {% trans "Published" context "Collection availability status" %}
  {% elif collection.publication_date is not None %}
    <div class="label">
      {% blocktrans with date=collection.publication_date context "Collection availability status" %}
        Hidden (will become visible on {{ date }})
      {% endblocktrans %}
    </div>
  {% else %}
    {% trans "Hidden" context "Collection availability status" %}
  {% endif %}
</div>

demo-app/templates/dashboard/includes/_filters.html
{% load i18n %}
{% load materializecss %}
{% load static %}


<div class="card">
  <form method="get">
    <div class="card-content">
      <div class="col s12">
        <span class="card-title">{% trans 'Filters' context 'Dashboard card title' %}</span>
        {{ filter.get_summary_message }}
        <span class="collapse-activate hide-on-large-only"><svg data-src="{% static 'images/filter-icon.svg' %}" /></span>
      </div>
      <div class="col s12 hide-on-large-only chips-container">
        {% for chip in chips %}
          <div class="chip">{{ chip.content|safe }} <a href="{{ chip.link }}">×</a></div>
        {% endfor %}
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="collapse">
      <div class="card-content card-action wide">
        <div class="row no-margin">
          {% for field in filter.form %}
            <div class="col s12">
              {% if field.name == 'sort_by' %}
                <!--Field 'sort_by' is hidden because it is rendered in header.
                This is required if you want to have sorting to be kept during further filtering.-->
                <input type="hidden" name="sort_by" value="{% if sort_by %}{{ sort_by }}{% endif %}">
              {% else %}
                {{ field|materializecss }}
              {% endif %}
            </div>
          {% endfor %}
        </div>
        <div class="clearfix"></div>
      </div>
      <div class="card-action">
        <div class="right-align">
          <div class="col s12">
            {% if filter.is_bound_unsorted %}
              <a href="." class="clear-filters btn-flat waves-effect">
                {% trans 'Clear' context 'Category page filters' %}
              </a>
            {% endif %}
            <button class="btn-flat waves-effect" type="submit">
              {% trans 'Filter' context 'Category price filter' %}
            </button>
          </div>
          <div class="clearfix"></div>
        </div>
      </div>
    </div>
  </form>
</div>

demo-app/templates/dashboard/includes/_google_preview.html
{% load build_absolute_uri from urls %}
{% load materializecss %}
{% load i18n %}
<div class='google-preview'>
  <span class="card-title">{% trans "Search engine listing preview" context "Title of the box showing preview from the search engine perspective" %}</span>
  <div class='google-preview__container'>
    <br>
    <div id="google-preview">
      <div class='google-preview__title'>
        <a id="google-preview-title" href='#'>{{ object.seo_title|default:"" }}</a>
      </div>
      <div class='google-preview__url'>
        {% if object.pk %}
          {% build_absolute_uri request=request location=object.get_absolute_url %}
        {% else %}
          {% build_absolute_uri request=request location="/" %}
        {% endif %}
      </div>
      <div id="google-preview-description" class='google-preview__description'>{{ object.seo_description|default:"" }}</div>
    </div>
  </div>
</div>
<div class="row">
  {{ form.seo_title|materializecss }}
</div>
<div class="row">
  {{ form.seo_description|materializecss }}
</div>

demo-app/templates/dashboard/includes/_menu_items.html
{% load i18n %}
{% load utils %}
{% load static %}
{% load status %}

<div class="card">
  <div class="card-content">
    <span class="card-title">
       {% trans "Menu items" context "Title of the menu items list" %}
    </span>
  </div>
  <div class="data-table-header-action">
    <a href="{% if root_item %}{% url "dashboard:menu-item-add" menu_pk=menu.pk root_pk=root_item.pk %}{% else %}{% url "dashboard:menu-item-add" menu_pk=menu.pk %}{% endif %}" class="btn-data-table btn-flat waves-effect">
      {% trans "Add" %}
    </a>
  </div>
  <div class="data-table-container">
    <table class="bordered highlight responsive data-table data-table-description">
      <thead>
        <tr>
          <th class="data-table-icon"></th>

          {% trans "Name" context "Menu items list table header name" as label %}
          {% sorting_header 'name' label is_wide=True %}

          {% trans "Points to" context "Menu items list table header points to" as label %}
          <th>{{ label }}</th>
          <th>{% trans "Status" context "Menu items status"%}</th>

          <th></th>
        </tr>
      </thead>
      <tbody class="sortable-items" data-post-url="{% if menu_item %}{% url 'dashboard:menu-items-reorder' menu_pk=menu.pk root_pk=menu_item.pk %}{% else %}{% url 'dashboard:menu-items-reorder' menu_pk=menu.pk %}{% endif %}" data-post-name="ordered_menu_items">
        {% for item in menu_items %}
          <tr data-action-go="{% url 'dashboard:menu-item-details' menu_pk=menu.pk item_pk=item.pk %}" class="sortable-item" data-id="{{ item.pk }}">
            <td class="data-table-icon ignore-link sortable__drag-area">
              <svg data-src="{% static "dashboard/images/reorder.svg" %}" height="20" width="20" fill="#000" />
            </td>
            <td>
              {{ item.name }}
            </td>
            <td>
              {{ item.destination_display }}
            </td>
            <td>
              {% if item.is_public %}
                <div class="label label-success">{% trans "Published" context "Menu items status"%}</div>
              {% elif item.page %}
                {% render_page_availability item.page %}
              {% else %}
                <div class="label label-danger">{% trans "Not published" context "Menu items status"%}</div>
              {% endif %}
            </td>
            <td class="right-align ignore-link">
              <a href="{% url 'dashboard:menu-item-edit' menu_pk=menu.pk item_pk=item.pk %}" class="btn-flat waves-effect">
                {% trans 'Edit' context 'Menu item edit action' %}
              </a>
              <a href="#base-modal" class="btn-flat waves-effect modal-trigger-custom" data-href="{% url 'dashboard:menu-item-delete' menu_pk=menu.pk item_pk=item.pk %}">
                {% trans "Remove" context "Menu item list action link" %}
              </a>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td colspan="4">{% trans "No menu items" context "Empty list of menu items" %}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% paginate menu_items %}

demo-app/templates/dashboard/includes/_page_availability.html
{% load i18n %}

{% if is_visible %}
  <div class="label label-{{ label_cls }}">
    {% trans "Published" context "Page availability status" %}
  </div>
{% elif not page.is_published %}
  <div class="label">
    {% trans "Hidden" context "Page availability status" %}
  </div>
{% elif page.publication_date %}
  <div class="label">
    {% blocktrans with date=page.publication_date context "Page availability status" %}
      Hidden (will become visible on {{ date }})
    {% endblocktrans %}
  </div>
{% else %}
  <div class="label">
    {% trans "Hidden" context "Page availability status" %}
  </div>
{% endif %}

demo-app/templates/dashboard/includes/_pagination.html
{% load i18n %}
{% load utils %}
{% load static %}


{% if page_obj.paginator.num_pages > 1 %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page=1"><svg data-src="{% static "dashboard/images/chevron-left.svg" %}" fill="#000" /></a></li>
      {% if page_obj.number|add:previous_section >= 1 %}
        <li><a href="{% construct_get_query page=page_obj.number|add:previous_section %}">&hellip;</a></li>
      {% elif page_obj.number|add:previous_section < 1 and page_obj.number|add:n_backward >= 1 %}
        <li><a href="?page=1">&hellip;</a></li>
      {% endif %}
    {% else %}
      <li class="disabled"><a href="#!"><svg data-src="{% static "dashboard/images/chevron-left.svg" %}" fill="#9E9E9E" /></a></li>
    {% endif %}

    {% for page in page_obj.paginator.page_range %}
      {% if page_obj.number == page %}
        <li class="active"><a href="{% construct_get_query page=page %}">{{ page }}</a></li>
      {% elif page > page_obj.number|add:n_backward and page < page_obj.number|add:n_forward %}
        <li class="waves-effect"><a href="{% construct_get_query page=page %}">{{ page }}</a></li>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      {% if page_obj.number|add:next_section <= page_obj.paginator.num_pages %}
        <li><a href="{% construct_get_query page=page_obj.number|add:next_section %}">&hellip;</a></li>
      {% elif page_obj.number|add:next_section > page_obj.paginator.num_pages and page_obj.number|add:n_forward <= page_obj.paginator.num_pages %}
        <li><a href="{% construct_get_query page=page_obj.paginator.num_pages %}">&hellip;</a></li>
      {% endif %}
      <li><a href="{% construct_get_query page=page_obj.paginator.num_pages %}"><svg data-src="{% static "dashboard/images/chevron-right.svg" %}" fill="#000" /></a></li>
    {% else %}
      <li class="disabled"><a href="#!"><svg data-src="{% static "dashboard/images/chevron-right.svg" %}" fill="#9E9E9E" /></a></li>
    {% endif %}
  </ul>
{% endif %}

demo-app/templates/dashboard/includes/_sorting_header.html
<th class="{% if is_wide %}wide{% endif %} {% if is_active %}active{% endif %}">
  <a href="{{ url }}">
    <svg data-src="{{ sorting_icon }}" />
    {{ label }}
  </a>
</th>